---
name: "Deploy: Live"

on:
  issue_comment:
    types: [created]

jobs:  
  parse:
    if: ${{ !github.event.issue.pull_request && github.event.comment.body == '/approve' }}
    runs-on: ubuntu-20.04
    outputs:
      output: ${{ steps.issue_body_parser.outputs.payload }}
    #  deploy-environment: ${{ fromJSON(steps.issue_body_parser.outputs.payload).environment }}
    #  ci-run-number: ${{ fromJSON(steps.issue_body_parser.outputs.payload).runNumber }}
    steps:
      - name: Comment on Issue      
        uses: peter-evans/create-or-update-comment@v1
        with:
          issue-number: ${{ github.event.issue.number }}
          body: 'Deployment Initiated 🚀'
          
      - name: Get Issue Data
        uses: peter-murray/issue-body-parser-action@v1
        id: issue_body_parser
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          issue_id: ${{ github.event.issue.number }}         
          payload: yaml

      - name: Test
        run: echo ${{ outputs.output }}
